name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build release
        run: |
          make
      - name: Upload release 
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./
