name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build release
        run: |
          rustc --version 
          cargo --version
          go version
          gcc -v
          mkdir ./release
          make
          mv ./test1 ./release/test1
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v0.1.6
        with:
         files: |
           ./target/release/your_binary  # 要上传的文件路径
         token: ${{ secrets.GITHUB_TOKEN }}
         release_name: Release ${{ github.run_number }}
         body: |
          released v1.1

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/test1 
          asset_name: test1  
          asset_content_type: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}
